pdf-engine: pdflatex
format:
  pdf:
    toc: false
    fig-pos: 'h'
header-includes:
    - \newcommand{\argmin}{\mathop{\mathrm{argmin}}\limits}
    - \usepackage{algorithm2e}
    - \usepackage{float}
    - \floatplacement{table}{H}
geometry: "left=3cm,right=3cm,top=2cm,bottom=2.5cm"
urlcolor: blue
toc-title: "Tabla de contenidos"
lang: es
nocite: '@*'
number-sections: true
execute:
  echo: false
  message: false
