## Análisis de Datos Topológicos (TDA)

El Análisis de Datos Topológicos o TDA es una área recientemente surgida de la ciencia de datos cuya principal motivación es la idea de que la topología y geometría proveen un acercamiento poderoso para inferir información robusta, cualitativa y a veces cuantitativa sobre la estructura de los datos [@IntroductionTDA]. El objetivo de esta sección es brindar una introducción a las herramientas y conceptos del TDA que utilizaremos para el desarrollo de esta Tesis.


### Espacios métricos {#sec-espacios-metricos}

Las cualidades topológicas y geométricas de un espacio están usualmente asociadas a espacios continuos, por lo que los datos representados como un conjunto finito de observaciones no revelan directamente ninguna información topológica por sí mismos. Una forma natural de destacar la estructura topológica de los datos es "conectar" los puntos que están "cerca" con el objetivo de exhibir una estructura global subyacente de los datos. La "cercanía" entre puntos se mide mediante una función de distancia, por lo que resulta conveniente considerar a los conjuntos de datos como muestras de un espacio métrico.

**Espacio Métrico**. Una espacio métrico $(M, \rho)$ es un conjunto $M$ con una función $\rho: M \times M \longrightarrow \mathbb{R}^{+}$, llamada distancia, tal que para cualquier trío de puntos $\mathbf{x}, \mathbf{y}, \mathbf{z} \in M$ se cumple:

I.  No negatividad: $\rho(\mathbf{x}, \mathbf{y}) \geq 0$ y $\rho(\mathbf{x}, \mathbf{y}) = 0$ solo sí $\mathbf{x} = \mathbf{y}$
II.  Simetría: $\rho(\mathbf{x}, \mathbf{y}) = \rho(\mathbf{y}, \mathbf{x})$
III.  Desigualdad triangular: $\rho(\mathbf{x}, \mathbf{z}) \leq \rho(\mathbf{x}, \mathbf{y}) + \rho(\mathbf{y}, \mathbf{z})$

Puede demostrarse [@PatuFermatDistance] que la distancia de Fermat desarrollada en la @sec-intro-fermat cumple las condiciones para ser una distancia según esta definición, por lo que pueden estudiarse las cualidades topológicas de un espacio métrico en base a esta misma.

#### Distancia de Hausdorff {#sec-hausdorff-distance}

Dados dos subconjuntos compactos $A, B \subseteq M$ la distancia de Hausdorff $d_H(A, B)$ entre $A$ y $B$ se define como el valor $\delta$ más pequeño tal que para cualquier $\mathbf{a} \in A$ existe un $\mathbf{b} \in B$ tal que $\rho(\mathbf{a}, \mathbf{b}) \leq \delta$ (Ver @fig-hausdorff-distance)

![Se ilustra la distancia de Hausdorff para el caso de dos curvas $X$ e $Y$, representando los subconjuntos $A, B \subseteq M$ siguiendo la notación de la @eq-hausdorff-distance. Si para todo punto en la curva gris se busca su punto más cercano en la curva verde, para posteriormente conservar la máxima de esas distancias, se obtienen los puntos $x$ e $y$ en la parte superior de la imagen. Por otro lado, si este proceso se realiza tomando ahora en cuenta todos los puntos de la curva verde, buscando su par más cercano en la curva verde, para posteriormente solo conservar la mayor de esas distancias, se obtiene la distancia marcada en línea punteada roja a la izquierda. Habiendo obtenido estas dos distancias, la mayor de ellas será la distancia de Hausdorff. Crédito de la imagen: [@ImagenHausdorff]](imagenes/hausdorff-distance.png){#fig-hausdorff-distance width=70%}

En otras palabras, si para todo subconjunto compacto $C \subseteq M$ denotamos $d(\cdot, C) : M \longrightarrow \mathbb{R}^{+}$ como la función de distancia a $C$, definida como
$$
d(\mathbf{x}, C) := \inf_{\mathbf{c} \in C} \rho(\mathbf{x}, \mathbf{c}), \quad \forall \mathbf{x} \in M
$$

Puede probarse que la distancia de Hausdorff entre $A$ y $B$ está definida mediante cualquiera de las siguientes igualdades

$$
\begin{split}
d_H(A, B) &= \max\{ \sup_{\mathbf{b} \in B} d(\mathbf{b}, A), \sup_{\mathbf{a} \in A} d(\mathbf{a}, B)\} \\
d_H(A, B) &= \sup_{\mathbf{x} \in M} |d(\mathbf{x}, A) - d(\mathbf{x}, B)| = ||d(\cdot, A) - d(\cdot, B)||_{\infty}
\end{split}
$$ {#eq-hausdorff-distance}

La distancia de Hausdorff provee una forma conveniente de cuantificar la proximidad entre diferentes conjuntos de datos provenientes del mismo espacio métrico.

### Homología {#sec-intro-homology}

La homología es un concepto fundamental en diversas ramas de las matemáticas, particularmente en la topología y geometría algebraica. Esta área de estudio se centra en comprender y clasificar las formas y estructuras espaciales de manera abstracta, permitiendo así la comparación y el análisis de diferentes espacios geométricos. La homología asocia entonces a cada espacio una serie de grupos, llamados grupos de homología, que reflejan características importantes del mismo, como pueden ser componentes conexos y agujeros de diversas dimensiones. Esta asignación se hace a a partir de la definición de los conceptos de "cadenas", "ciclos" y "bordes":
Una cadena es una combinación formal de elementos geométricos, como pueden ser puntos, curvas o superficies. Un borde se define como una cadena que actúa de frontera de una cadena de dimensión superior, se define entonces el operador borde $\partial$ que mapea cadenas de dimensión $k$ (o $k$-cadenas) a $(k-1)$-cadenas. A partir de la noción de borde, se define a los ciclos como cadenas $c$ sin frontera, es decir $\partial c = 0$. Estos representan intuitivamente "agujeros" en diversas dimensiones. En particular, a lo largo de este trabajo, haremos foco mayoritariamente en la homología de grado uno, denotada como $\Pi_1$, que puede ser interpretada, de la forma más intuitiva posible, como la cantidad de ciclos unidimensionales diferentes, donde por "diferentes" nos referimos a que no pueden ser deformados dentro de la variedad hasta ser iguales entre sí. Si la variedad $\mathcal{M}$ presenta entonces un único agujero de estas características, esto se denota como:

$$
\Pi_1(\mathcal{M}) = \mathbb{Z}
$$

Siendo uno la dimensión del espacio que representa la homología de la variedad, es decir
$$
\mathrm{dim}(\Pi_1(\mathcal{M})) = \beta_1(\mathcal{M}) = 1
$$

A la cantidad $\beta_1$, o en general, $\beta_k$ para homologías de grado superior, se la conoce como el $k$-ésimo número de *Betti*.

Otro grado de homología que mencionaremos brevemente será el de las componentes conexos, denotado como $\Pi_0$, que intuitivamente representa todos los puntos que pueden ser unidos mediante una curva sin salirse de la variedad.

<!-- ACA CAMBIE H por PI, hay que ver como funciona -->

![Se ilustra la homología de primer grado de un toro, marcando en azul las dos curvas del mismo que no pueden ser continuamente deformadas la una en la otra. Cualquier otra curva cerrada que elijamos sobre el toro, podrá ser deformada en alguna de estas dos. Crédito de la imagen: [@IntroductionTDA]](imagenes/homology-torus.png){#fig-torus-homology  width=50%}


### Homología persistente {#sec-intro-persistent-homology}

A partir de la definición general de Homología desarrollada en la @sec-intro-homology, el problema fundamental que se busca abordar con el Análisis Topológico de Datos (TDA) es inferir la homología en cuestión de una dada variedad $\mathcal{M}$ a partir de una muestra $\mathcal{S}_N$, obtenida mediante una función de densidad $f$ con soporte en $\mathcal{M}$. Como se mencionó brevemente en la @sec-espacios-metricos, esto se realiza mediante la elección de una medida de distancia. Concretamente, se define el espacio generado por una unión de bolas de radio $\epsilon$ centradas en las muestran de $\mathcal{S}_N$, es decir

$$ \mathcal{S}_N^{\epsilon} = \cup_{\mathbf{x} \in \mathcal{S}_N} B(\mathbf{x}, \epsilon)$$

Donde
$$
B(\mathbf{x}_i, \epsilon) = \{ \mathbf{x} \mid d(\mathbf{x}_i, \mathbf{x}) < \epsilon \}
$$

con $d(\cdot, \cdot)$ una función de distancia.
Se demuestra en [@ConfidenceSetsForPersistenceDiagrams] que cuando $\mathcal{M}$ es una variedad compacta y suave, bajo condiciones poco restrictivas sobre la distancia de Hausdorff (definida en la @sec-hausdorff-distance) entre la muestra y la variedad de la que proviene $d_{H}(\mathcal{S}_N, \mathcal{M})$, y una elección apropiada del valor $\epsilon$, entonces el espacio $\mathcal{S}_N^{\epsilon}$ es topológicamente equivalente a $\mathcal{M}$ [@Niyogi2008]. Esto significa que podemos inferir la topología de $\mathcal{M}$ a partir de $\mathcal{S}_N^{\epsilon}$. Se ilustra este concepto en la @fig-topologia-equivalente.

![Se ilustra en la imagen el conjunto de datos $\mathcal{S}_N$ (esquina superior izquierda, denotado como $\mathbb{X}_n$) y los espacios $\mathcal{S}_N^{\epsilon}$ (denotados en la imagen como $\mathbb{X}_n^{r_i}$) para tres diferentes valores de $\epsilon$. Se observa como el conjunto de datos parece provenir de una variedad que presenta un agujero en su interior, pero esto deja de ser apreciable para el valor de $\epsilon$ más grande en la esquina inferior derecha. Crédito de la imagen: [@IntroductionTDA]](imagenes/topologia-equivalente-epsilon.png){#fig-topologia-equivalente width=60%}

En la práctica, este enfoque resulta en dos problemas fundamentales

1. A pesar de ser posible, resulta complejo inferir la topología a partir de $\mathcal{S}_N^{\epsilon}$. Es por esto que se introducen los complejos simpliciales, los cuales desarrollaremos en la @sec-intro-simplex-complex, para eficientizar el cómputo.

2. La elección del $epsilon$ apropiado no resulta obvia. Como se observa en la @fig-topologia-equivalente la homología de $\mathcal{S}_N^{\epsilon}$ varía con la elección de $\epsilon$. La respuesta a este problema viene dada por las técnicas de homología persistente, que esencialmente consisten en evaluar la homología de $\mathcal{S}_N^{\epsilon}$ no solo para un valor de $epsilon$, si no para un rango de valores lo suficientemente grande. La homología persistente busca resumir como las cualidades topológicas de $\mathcal{S}_N^{\epsilon}$ cambian a medida que varía el valor de $\epsilon$, por ejemplo los agujeros pueden aparecer o cerrarse a medida que el radio de las bolas aumenta.

Este procedimiento da como resultado un gráfico conocido como "diagrama de persistencia" que resume este procedimiento, descrito a continuación.


#### Diagrama de persistencia {#sec-intro-diagramas-persistencia}

El procedimiento de variar $\epsilon$ y evaluar las cualidades topológicas de $\mathcal{S}_N^{\epsilon}$ para cada valor da como resultado un tiempo de nacimiento $b_i$ en el que la cualidad topológica $i$ aparece en $\mathcal{S}_N^{\epsilon}$ y un valor de muerte $d_i$, en el que esa misma cualidad desaparece. Un caso de esto sería por ejemplo el valor de $\epsilon$ en el que un agujero aparece y el valor en el que todo el espacio de este agujero es tapado por las bolas $B(\mathbf{x}_i, \epsilon)$, tomando como referencia la @fig-topologia-equivalente, se observa que para el primer valor de $\epsilon$ ya es apreciable el agujero, por lo que ya se tendría el valor de nacimiento $b_i$, mientras que para el último valor del radio de las bolas en la esquina inferior derecha el agujero ya no es apreciable, por lo que a esta altura se obtendría el valor de muerte $d_i$ de la cualidad.

Al combinar estos valores de nacimiento y muerte obtenemos un par ordenado $(b_i, d_i)$ para cada cualidad topológica, que si son dispuestos conjuntamente en un plano dan lugar al diagrama de persistencia. Este procedimiento constructivo se ilustra en la figura @fig-intro-persistence-diagram, donde se representa para distintos valores de $\epsilon$ el nacimiento de una cualidad topológica como una barra, correspondiendo el color rojo a una componente conexa y el azul a un agujero de primer orden. En un inicio, cada punto es su propia componente conexa, pero a medida que el radio de la bola comienza a aumentar, solo se preserva una única componente conexa correspondiente a la unión de todas las bolas. Por su parte, al momento en el que las bolas logran unirse por primera vez, se observa el nacimiento de los dos agujeros, representados como dos barras azules. Se observa que el agujero inferior es más pequeño y que sus puntos son más dispersos, por lo que esa cualidad topológica nace después y muere antes. En la esquina inferior izquierda de la imagen se observa como ya todas las cualidades encontraron su $\epsilon$ de muerte, por lo que pueden ser finalmente representadas en el diagrama de persistencia, en el que la altura de cada barra se preserva por sobre la diagonal, indicando el eje $x$ el momento de nacimiento y el $y$ el de muerte de la cualidad.


El diagrama de persistencia representa una medida de resumen sobre las características topológicas de los datos utilizados. Puntos cercanos a la diagonal en el diagrama representan cualidades topológicas con corto tiempo de vida y serán consideradas como "ruido topológico", esto se ilustra en la @fig-intro-noise-persistence-diagram, donde se observa la secuencia constructiva del diagrama de persistencia para una circunferencia ruidosa. Se observa como en el proceso "nacen" cualidades topológicas espurias, que no corresponden a lo que debería ser el diagrama de persistencia de una circunferencia ideal (una única componente de primer grado). Si bien estas son efectivamente componentes que nacen y mueren en diferentes $\epsilon$, su tiempo de vida es muy inferior al del agujero real, por lo que se posicionarán más cerca de la diagonal en el diagrama de persistencia resultante.
Las aplicaciones están usualmente interesadas en cualidades que pueden ser distinguidas del ruido, es decir, cualidades que persisten para un amplio rango de valores $\epsilon$ [@ConfidenceSetsForPersistenceDiagrams; @DynamicalSystemsFeaturePersistentHomology; @TopologicalTimeSeriesPersistentHomology; @DelayEmbeddingsWheezeDetectionPersistentHomology]. Es el rol de los test de hipótesis el de determinar bajo cierto nivel de confianza cuáles características topológicas son distintas a ruido.

![Ilustración del proceso constructivo del diagrama de persistencia para un conjunto de datos provenientes de una figura similar a la de un número ocho. Distintos valores de $\epsilon$ se corresponden con la representación del conjunto $\mathcal{S}_N^{\epsilon}$ construido a partir de los datos y a su lado un diagrama de barras donde cada barra representa el tiempo de vida de cada una de las cualidad topológicas que nacieron hasta el momento. Crédito de la imagen: [@IntroductionTDA]](imagenes/intro-persistence-diagram.png){#fig-intro-persistence-diagram width=80%}

![Construcción del diagrama de persistencia para datos provenientes de una circunferencia ruidosa. Se incluyen solamente las cualidades topológicas de primer grado, ignorando las componentes conexas. Cada ciclo se ilustra desde el $\epsilon$ de su nacimiento hasta su muerte con un color diferente, esta duración resultando es finalmente representada bajo el mismo color en el diagrama de persistencia final. Crédito de la imagen: [@ParamethricInferencePersistenceDiagrams]](imagenes/noise-persistence-diagram.png){#fig-intro-noise-persistence-diagram width=100%}


##### Distancia entre diagramas de persistencia {#sec-distancia-diagramas}

Sean $\mathcal{X}$ y $\mathcal{Y}$ dos diagramas de persistencia, resulta natural preguntarse cómo estos pueden ser comparados entre sí. Más aún, si los conjuntos de datos que dieron lugar a los diagramas de persistencia $\mathcal{X}$ y $\mathcal{Y}$ son muy distintas, serán también estos diagramas resultantes muy disimiles? Para responder estas preguntas se debe definir la noción de distancia entre diagramas de persistencia conocida como distancia _bottleneck_ [@IntroductionComputationalTopology].

Sean entonces $\mathcal{X}$ e $\mathcal{Y}$ dos diagramas de persistencia, para definir la distancia _bottleneck_ entre estos consideraremos una biyección $\eta : \mathcal{X} \rightarrow \mathcal{Y}$, es decir, una función que le asigna a cada punto $x \in  \mathcal{X}$ un punto $y \in  \mathcal{Y}$ y viceversa. guardaremos el supremo de las distancias entre puntos correspondientes a cada diagrama, midiendose esta distancia como

$$|| x - y ||_{\infty} = \max\{|x_1 - y_1|, |x_2 - y_2|\}$$


entonces se define la distancia _bottleneck_ $W_{\infty}(\mathcal{X}, \mathcal{Y})$ en la @eq-bottleneck-distance

$$
W_{\infty}(\mathcal{X}, \mathcal{Y}) = \inf_{\eta : \mathcal{X} \rightarrow \mathcal{Y}} \sup_{x \in \mathcal{X}} || x - \eta(x) ||_{\infty}
$$ {#eq-bottleneck-distance}

Cabe mencionar la posibilidad de que $\mathcal{X}$ e $\mathcal{Y}$ no cuenten con la misma cantidad de puntos, en cuyo caso, se considera que ambos diagramas de persistencia también poseen infinitos puntos en su diagonal, estos puntos se utilizarán en la medida que sean necesarios para formar la biyección $\eta : \mathcal{X} \rightarrow \mathcal{Y}$.

La distancia _bottleneck_ entonces se calcula como la mayor distancia entre dos pares de puntos correspondientes a la biyección que minimiza esta máxima distancia
En la @fig-intro-bottleneck-distance se ilustra el cálculo de esta distancia, En la que se dibujó un cuadrado de lado dos veces la distancia _bottleneck_ centrado en cada uno de los puntos de $\mathcal{X}$, de forma que este cuadrado contenga a su par correspondiente en $\mathcal{Y}$

![Superposición de dos diagramas de persistencia con puntos agregados en la diagonal para completar la biyección. La distancia _bottleneck_ es equivalente a la mitad del lado de los cuadrados que ilustran la biyección. Crédito de la imagen: [@IntroductionComputationalTopology]](imagenes/bottleneck-distance.png){#fig-intro-bottleneck-distance width=60%}

Resulta evidente que $W_{\infty}(\mathcal{X}, \mathcal{Y}) = 0$ solo sí $\mathcal{X} = \mathcal{Y}$, más aún, $W_{\infty}(\mathcal{X}, \mathcal{Y}) = W_{\infty}(\mathcal{Y}, \mathcal{X})$ y $W_{\infty}(\mathcal{X}, \mathcal{Z}) \leq W_{\infty}(\mathcal{X}, \mathcal{Y}) + W_{\infty}(\mathcal{Y}, \mathcal{Z})$ por lo que la distancia _bottleneck_ cumple todos los axiomas de una métrica y merece ser llamada una distancia [@IntroductionComputationalTopology].

Una desventaja de la distancia _bottleneck_ es su falta de sensibilidad a detalles de la biyección por fuera de la distancia entre puntos a máxima distancia de la misma. Para sobrellevar esta desventaja, se introduce la distancia de _Wasserstein_ de grado $q$. Esta distancia reemplaza el cálculo del supremo en la distancia _bottleneck_ mediante la suma de las $q$-ésima potencias  de las distancias $|| x - \eta(x) ||_{\infty}$, nuevamente, minimizando para todas las biyecciónes posibles y finalmente tomando la raiz $q$-ésima, como se ilustra en la @eq-wasserstein-distance

$$
W_q(\mathcal{Y}, \mathcal{X}) = \left( \inf_{\eta : \mathcal{X} \rightarrow \mathcal{Y}} \sum_{x \in \mathcal{X}} || x - \eta(x) ||_{\infty}^q \right)^{1/q}
$$ {#eq-wasserstein-distance}

Como la similitud entre la notación de las ecuaciones [-@eq-bottleneck-distance] y [-@eq-wasserstein-distance] lo sugiere, la distancia _bottleneck_ es el límite de la distancia _Wasserstein_ para $q$ tendiendo a infinito. Análogamente a la distancia _bottleneck_, es fácil verificar que $W_q$ satisface los requerimientos de una métrica y también merece ser llamada distancia [@IntroductionComputationalTopology]

Estas distancias definidas son de suma importancia ya que se logra probar para cada una de ellas, mediante los teoremas de estabilidad que las mismas están acotadas por la distancia real que existe entre los espacios topológicos subyacentes que dan lugar a los conjuntos de datos sobre los cuáles se calculan los diagramas de persistencia [@IntroductionComputationalTopology]

#### Complejos simpliciales {#sec-intro-simplex-complex}

Como se mencionó previamente, calcular la homología $H(\mathcal{M})$ directamente a partir de $\mathcal{S}_N^{\epsilon}$ resulta una tarea difícil, por lo que esto se realiza mediante la construcción del complejo simplicial a partir de $\mathcal{S}_N$. Un complejo simplicial es un conjunto de símplices, siendo estos generalizaciones de un triángulo en dimensiones arbitrarias, definidos al conectar puntos a menos distancia que $\epsilon$. En particular, un complejo simplicial muy utilizado en topología computacional es el complejo de Čech. El complejo denotado como $Čech(\mathcal{S}_N, \epsilon)$ representa el conjunto de símplices $\sigma$ con vértices $\mathbf{v}_1, \cdots, \mathbf{v}_k \in \mathcal{S}_N$ tales que

$$ \bigcap_{i=1}^k B(\mathbf{v}_i, \epsilon) \neq \emptyset $$

El teorema del Nervio garantiza que $\mathcal{S}_N^{\epsilon}$ y $Čech(\mathcal{S}_N, \epsilon)$ son homotópicamente equivalentes [@ConfidenceSetsForPersistenceDiagrams; @NerveTheorem], es decir, comparten la misma homología.

Por cuestiones de eficiencia computacional, es común aproximar el complejo de Čech con el complejo de Vietoris-Rips [@ConfidenceSetsForPersistenceDiagrams], denotado como $V(\mathcal{S}_N, \epsilon)$, que consiste en los símplices con vértices en $\mathcal{S}_N$ de diámetro máximo $2\epsilon$. En otras palabras, el símplice $\sigma$ es incluido en el complejo si cada par de vértices en $\sigma$ está separado como máximo a distancia  $2\epsilon$. Este complejo resulta de cálculo más eficiente que el de Čech ya que solo las distancias de a pares entre los puntos son necesarias, y el mismo cumple la siguiente igualdad [@ConfidenceSetsForPersistenceDiagrams]:

$$
Čech(\mathcal{S}_N, \epsilon) \subset V(\mathcal{S}_N, \epsilon) \subset Čech(\mathcal{S}_N, \sqrt{2}\epsilon)
$$

Por lo que si se evalúa para un rango de valores de $\epsilon$, las conclusiones a las que se llegará en cuanto a la homología de  $\mathcal{S}_N$ serán equivalentes. En particular, el diagrama de persistencia será análogo. En la @fig-cech-vs-rips se ilustra la diferencia entre estos dos complejos simpliciales.

![Conjunto de datos de 6 puntos sobre el cual se construyen los complejos de Čech ($Čech(\mathcal{S}_N, \epsilon)$) y Vietoris-Rips ($V(\mathcal{S}_N, \epsilon)$). El símplice gris corresponde a ambos complejos, ya que la intersección entre las bolas de los tres puntos que lo conforman es no nula, por su parte, el símplice celeste solo pertenece a $V(\mathcal{S}_N, \epsilon)$, ya que las bolas que lo conforman tienen intersecciones no nulas de a pares (la distancia entre ellos es menor a $2\epsilon$), pero no en conjunto. Crédito de la imagen: [@ImagenRipsVsVietorisClara]](imagenes/cech-vs-rips-2.png){#fig-cech-vs-rips width=60%}


#### Diagramas de persistencia de conjuntos de nivel  {#sec-intro-dgm-function}

Hasta el momento se discutió cómo estimar la homología de $\mathcal{M}$ a partir de una muestra $\mathcal{S}_N$ variando un parámetro $\epsilon$ y construyendo las bolas $B(\mathbf{x}_i, \epsilon)$ que puede demostrarse conservan la homología del espacio original para un $\epsilon$ desconocido, por lo que él mismo se varía construyendo el diagrama de persistencia, este proceso fue ilustrado en la @fig-intro-persistence-diagram. Una observación que puede hacerse de este procedimiento es que la unión de bolas $B(\mathbf{x}_i, \epsilon)$ puede definirse, alternativamente, como los conjuntos de nivel inferiores de una función $f(\mathbf{x})$, siendo esta el mínimo de la función de distancia entre el punto $\mathbf{x}$ y los datos de la muestra, es decir:
$$
L_{\epsilon} = \cup_{\mathbf{x} \in \mathcal{S}_N} B(\mathbf{x}, \epsilon) = \{ \mathbf{x} \mid \min_{\mathbf{x}_i \in \mathcal{S}_N}d(\mathbf{x}_i, \mathbf{x}) < \epsilon \}
$$

Esta observación, que se ilustra en la @fig-distance-persistence-diagram, abre las puertas a que el diagrama de persistencia pueda expresarse en términos más generales reemplazando la función $\min_{\mathbf{x}_i \in \mathcal{S}_N}d(\mathbf{x}_i, \mathbf{x})$ por alguna otra función arbitraria $g(\mathbf{x})$, cuyos conjuntos de nivel serán utilizados para construir el diagrama de persistencia y así estimar la homología de $\mathcal{M}$. En la @fig-g-persistence-diagram se observa un ejemplo de este procedimiento para una función escalar arbitraria.
Para algunas funciones $g$, como por ejemplo la correspondiente a la estimación de densidad de probabilidad por ventanas [@ConfidenceSetsForPersistenceDiagrams], la homología reproducida conserva las cualidades topológicas del espacio original pero con ventajas adicionales como pueden ser mayor robustez ante datos atípicos o ruido, es por esto que la inferencia de las cualidades topológicas del espacio original $\mathcal{M}$ puede realizarse directamente sobre un diagrama de persistencia construido con los conjuntos de nivel de alguna otra función $g(x)$. En términos prácticos y computacionales, este diagrama de persistencia se construye a partir de evaluar la función bajo análisis sobre una grilla de puntos dentro del espacio a analizar, y una vez obtenidos estos valores realizar una interpolación para construir el diagrama [@ConfidenceSetsForPersistenceDiagrams; @CubicalPersistentDiagrams; @GudhiDoc].


![Diagrama de persistencia para tres muestras a partir de la función de mínima distancia a algún punto del conjunto (denotada como $s = min_{\mathbf{x}_i \in \mathcal{S}_N}d(\mathbf{x}_i, \mathbf{x})$ en la figura). Se observa que comenzando con $s<0$, se tienen tres componentes centradas en los puntos (es por eso que en el diagrama de persistencia todas las componentes comienza en cero), esto cambia cuando se alcanza el conjunto de nivel $s<1$, donde las bolas de las dos primeras muestras se unirían, bajo este enfoque se muestra que la función deja por debajo el primer triángulo, uniendo los soportes para los cuales esas dos muestras estaban a menos de uno de distancia. Finalmente, lo mismo sucede al alcanzar $s<2$, donde todos los conjuntos de nivel se unen, formándose así la última componente conexa que se mantiene hasta $\infty$. Crédito de la imagen: [@ConfidenceSetsForPersistenceDiagrams]](imagenes/distance-persistence-diagram.png){#fig-distance-persistence-diagram width=80%}

![Diagrama de persistencia de los conjuntos de nivel de una función arbitraria $y(x)$. Se observa que, comenzando en $y=0$, el conjunto de nivel $y<0$ es nulo, esto cambia cuando se llega al valor $y<a_1$, en donde el primer intervalo comienza a aparecer. En los valores $y<a_2$ e $y<a_3$ aparecen nuevos intervalos en los mínimos locales de la función. Cuando se alcanza $y<a_4$ dos de estos intervalos se unen, y al alcanzarse $y<a_5$ este último se junta con el iniciado en $y<a_1$ que termina en $y<a_6$. De esta forma, para las cualidades topológicas resultantes, se obtienen los tiempos de nacimiento $b_i = a_1, a_2, a_3$ y sus respectivos tiempos de muerte $d_i = a_6, a_5, a_4$, siendo estos los puntos que se grafican en el diagrama de persistencia. Crédito de la imagen: [@IntroductionTDA]](imagenes/g-persistence-diagram.png){#fig-g-persistence-diagram width=80%}
