## Intervalos de confianza {#sec-intro-intervalos}

En estadística frecuentista, un intervalo de confianza es un rango estimado para un parámetro desconocido. El intervalo de confianza se calcula a un nivel designado, siendo el nivel de confianza de $95\%$ el más utilizado. El nivel de confianza representa la proporción teórica de intervalos de confianza que contiene al verdadero valor del parámetro. Por ejemplo, de todos los intervalos computados al nivel $95\%$ para diferentes conjuntos de datos del mismo tamaño obtenidos a partir de la misma distribución, el $95\%$ de ellos deberían contener al verdadero valor [@IntroductoryStats]

Formalmente, sea $X$ una muestra aleatoria proveniente de una distribución de probabilidad $p$ de parámetro unidimensional $\theta$, siendo $\theta$ la cantidad a estimar. Un intervalo de confianza de nivel $1 - \alpha$ para el parámetro $\theta$ es el intervalo $(\theta_L(X), \theta_U(X))$ determinado por las variables aleatorias $\theta_L(X)$ y $\theta_U(X)$ tales que la siguiente igualdad se cumple para todo $\theta$

$$
\mathbb{P}\{ \theta_L(X) \leq \theta \leq \theta_u(X) \} = 1 - \alpha
$$ {#eq-definicion-ci}

Para el caso de parámetros de dimensionalidad mayor, es decir $\boldsymbol{\theta} = \left[\theta_1, \dots, \theta_K \right]$, se habla de "regiones de confianza", siendo la intuición de estas equivalente a la del caso unidimensional, pero admitiendo regiones $A(X)$ de cualquier forma, es decir $\mathbb{P}\{ \boldsymbol{\theta} \in A(X) \} = 1 - \alpha$.


### Relación entre intervalos de confianza y pruebas de hipótesis

Resulta importante para el desarrollo de esta Tesis analizar la relación que existe entre test de hipótesis e intervalos de confianza, ya que utilizaremos los intervalos de confianza construidos sobre diagramas de persistencia para evaluar, mediante pruebas de hipótesis, la existencia de cualidades topológicas. Recordando la definición de intervalo de confianza dada por \eqref{eq-definicion-ci}, imaginemos que queremos verificar que nuestro parámetro es distinto a algún valor $\theta_0$, como por ejemplo $\theta_0 = 0$, resulta intuitivo pensar que podemos calcular un intervalo de confianza de nivel $1 - \alpha$ para este parámetro y verificar si el mismo contiene o no a nuestro valor de interés $\theta_0$, en caso de no contenerlo, y recordando que por definición el intervalo de confianza calculado con el estadístico de la muestra tiene una probabilidad de $(1 - \alpha)$ de contener a nuestro parámetro real, podemos descartar la hipótesis $H_0: \theta = \theta_0$ con un nivel de confianza $1 - \alpha$.


### Cálculo de intervalos de confianza

En algunas situaciones controladas los intervalos de confianza pueden calcularse de forma analítica con fórmula cerrada, como es el típico caso del intervalo de confianza para la media de una distribución gaussiana. En otros casos, estos intervalos resultan de muy difícil o incluso imposible cálculo, al no tener expresión cerrada, es por esto que surgen estrategias computacionales de simulación para calcularlos, de las cuales destacan aquellas que utilizan remuestreo para obtener nuevos conjuntos de datos y estimar así los intervalos de confianza. Dos de las estrategias más conocidas de remuestreo son el *Bootstrap* y el sub-muestreo, que serán utilizadas para estimar nuestros intervalos de confianza de cualidades topológicas. A continuación se describen ambas técnicas

#### *Bootstrap* {#sec-intro-bootstrap}

El *Bootstrap* es una técnica que busca hacer inferencia sobre una población a partir de una muestra de la misma. La principal idea es que es posible realizar inferencia sobre la muestra a partir de un remuestreo de la misma. Dado que la población es desconocida, el verdadero error del estadístico de la muestra contra el valor de la población es desconocido, pero en los remuestreos *bootstrap* la "población" es de hecho la muestra, que si es conocida, por lo que la calidad de la inferencia sobre la muestra a partir del remuestreo es medible

Más formalmente, *bootstrap* trata al problema de inferencia sobre la verdadera distribución de probabilidad $P$ dada la muestra original como análogo al problema de inferencia sobre la distribución empírica $\hat{P}$ a partir de la muestras *bootstrap*, es decir, remuestreo con reposición de igual tamaño que la muestra original [@IntroBootstrap; @WikiBootstrap].
La calidad de la inferencia respecto a $\hat{P}$ puede ser evaluada ya que esta distribución es conocida, y si $\hat{P}$ es una aproximación razonable de $P$, entonces la calidad de inferencia sobre la misma distribución $P$ puede ser inferida.
A fines prácticos, dada una muestra i.i.d $\mathcal{S}_{N} = \{x_1, \dots, x_N\}$ se obtienen $M$ muestras *bootstrap* $\mathcal{S}_N^j, \ j = 0, \dots, M$ a partir del remuestreo con reposición de tamaño $N$ sobre $\mathcal{S}_{N}$. A partir de estas muestras *bootstrap*, la distribución del estadístico $\hat{\theta} = T(\mathcal{S}_{N})$ puede ser inferida analizando la distribución empírica de $\hat{\theta}^j = T(\mathcal{S}_N^j)$

#### Sub-muestreo {#sec-intro-subsampling}

Otra técnica proveniente del remuestreo que es utilizada como alternativa al *bootstrap* es el sub-muestro. Esta técnica se basa en utilizar subconjuntos de la muestra original para evaluar el estimador en cuestión y obtener una noción de variabilidad del mismo [@SubsamplingAndHalf]. Formalmente, dada una muestra $\mathcal{S}_{N} = \{x_1, \dots, x_N\}$, el sub-muestreo consiste en obtener muestras aleatorias sin reposición de tamaño $b$ de $\mathcal{S}_{N}$, con $b < N$, es decir, obtener aleatoriamente sequencias de los $\binom{N}{b}$ conjuntos posibles que se forman al tomar $b$ elementos de $\mathcal{S}_{N}$, a la que llamaremos $\mathcal{S}_{N, b}^j, \ j = 0, \dots, M$ y calcular el estadísco a partir de esta sub-muestra $\hat{\theta}_{b}^j = T(\mathcal{S}_{N, b}^j)$. Al repetir este procedimiento para una cantidad lo suficientemente grande de $M$, podemos obtener la distribución del estadístico, y en particular, un intervalo de confianza para el mismo al tomar los percentiles de la distribución empírica de $\hat{\theta}_{b}^j$, análogamente a lo realizado para el *bootstrap*.

Este método resulta consistente en casos en los que el *bootstrap* no lo es [@SubsamplingAndHalf], pero introduce la complejidad de la elección de el tamaño de sub-muestras $b$

## Regiones de confianza para diagramas de persistencia {#sec-homologia-intervalos}

Resulta natural preguntarse cómo se aplican las regiones de confianza, desarrollados en la @sec-intro-intervalos, a los diagramas de persistencia introducidos en la  @sec-intro-diagramas-persistencia. En este caso, no es un parámetro de una distribución sobre el cual se busca obtener una estimación de la región de confianza, sino de las cualidades topológicas de la variedad $\mathcal{M}$ del que provienen nuestros datos. Para lograr esto se busca, dado un nivel $1 - \alpha$, encontrar el estadístico $\theta_n$ tal que

$$
\lim_{n \rightarrow \infty} \inf \mathbb{P}(0 \leq W_\infty(\mathcal{P}, \hat{\mathcal{P}}) \leq \theta_n) \geq 1 -  \alpha
$$ {#eq-ci-persistence-diagram}

con $\mathcal{P}$ el diagrama de persistencia de la variedad $\mathcal{M}$, definido a partir de los conjuntos de nivel $\{ \mathbf{x} \mid d_\mathcal{M}(\mathbf{x}) < \epsilon \}$ de la función de distancia a la variedad, expresada como:
$$ d_\mathcal{M}(\mathbf{x}) = \inf_{\mathbf{y} \in \mathcal{M}} ||\mathbf{x} - \mathbf{y} || $$

Y siendo $\hat{\mathcal{P}}$ el diagrama de persistencia construido con el conjunto de datos $\mathcal{S}_{N}$ que busca estimar $\mathcal{P}$.

La región de confianza resultante puede visualizarse centrando una caja de lado $2 \theta_n$ en cada punto $p = (b_i, d_i)$ del diagrama de persistencia. El punto en cuestión es considerado indistinguible de ruido si la caja correspondiente, formalmente definida como $\{ q \in \mathbb{R}^2 : ||q - p ||_{\infty} \leq \theta_n \}$, interseca con la diagonal.
Alternativamente, la región de confianza puede visualizarse añadiendo una banda de ancho $\sqrt{2} \theta_n$ alrededor de la diagonal del diagrama de persistencia. La interpretación de esta banda sería la siguiente: Puntos dentro de la banda no son significativamente diferentes de ruido, puntos por fuera de la banda representan una característica topológica significativa. Dicho en otras palabras, si la región de confianza de un punto toca la diagonal, no podemos descartar que el tiempo de vida de esa cualidad topológica sea nulo, por lo que consideramos que es en realidad ruido. En la @fig-interval-persistence-diagram se ilustran las regiones de confianza de ambas formas.

Es posible entonces construir pruebas de hipótesis para diagramas de persistencia de la siguiente forma: Asumamos que estamos interesados en probar, con un nivel de significancia $1 - \alpha$, que una dada cualidad topológica está presente en nuestra variedad $\mathcal{M}$, de la cual provienen los datos. Para lograr esto, basta con evaluar si la componente $p_i = (b_i, d_i)$ del diagrama de persistencia $\hat{\mathcal{P}}$ es significativa, esto puede expresarse como la siguiente hipótesis nula:

$$
H^{i}_0: l_i = d_i - b_i = 0
$$

que se buscará rechazar en pos de aceptar la hipótesis alternativa, dada por

$$
H^{i}_1: l_i > 0
$$

Este *test* se realiza en simultáneo para todas las cualidades topológicas del diagrama $\hat{\mathcal{P}}$ con un nivel $1 - \alpha$.
Continuando el razonamiento ilustrado en la @fig-interval-persistence-diagram, si una dada cualidad topológica $p_i$ se encuentra a una distancia menor a $\sqrt{2} \theta_n$ de la diagonal, entonces la hipótesis nula $H_0^{i}$ para esa cualidad topológica no puede ser rechazada. Otra forma de entender este razonamiento es la siguiente: Todos los posibles diagramas de persistencia $\tilde{\mathcal{P}}$ que están dentro de nuestra región de confianza de nivel $1 - \alpha$ se denotan como

$$
\mathcal{C}_n = \{\tilde{\mathcal{P}} : W_\infty(\tilde{\mathcal{P}}, \hat{\mathcal{P}}) < \theta_n \}
$$ {#eq-confidence-set}

por lo que podemos mover cada uno de los puntos $p_i$ del diagrama de persistencia dentro de la caja de lado $2 \theta_n$ centrada en $p_i$ sin salirnos de esa región de confianza. Si al realizar este procedimiento no podemos llevar al punto $p_i$ a la diagonal, esto significa que la cualidad topológica que representa $p_i$ no puede ser interpretada como ruido bajo un *test* de nivel $1 - \alpha$, ya que no existe un $\tilde{\mathcal{P}}$ que no posea esa cualidad. Entonces, si bien la región de confianza se construye para todo el diagrama de persistencia, es posible extraer información de cada una de las cualidades topológicas $p_i$ individualmente de esta forma.

Resulta importante destacar que la región de confianza resultante de \eqref{eq-ci-persistence-diagram} es asintótica, por lo que en términos prácticos los resultados obtenidos mantendrán este nivel estadístico sólo para muestras $n$ suficientemente grandes. El valor de $n$ necesario dependerá de la homología subyacente y de la función de distancia utilizada, ya que se espera que al utilizar la distancia de Fermat, se obtengan resultados más consistentes con la verdadera homología de la variedad $\mathcal{M}$ para menores $n$.

Una observación relevante que se realiza en [@ConfidenceSetsForPersistenceDiagrams] sobre este procedimiento es que esta forma dicotómica de clasificar las componentes topológicas en "señal" o "ruido" no es la única posible, ya que en realidad la región de confianza construida da lugar, para un tamaño de muestra $n$, a un conjunto de variedades con diagramas de persistencia, expresados en la @eq-confidence-set. Esta definición de $\mathcal{C}_n$ da lugar a formas mucho más elaboradas de cuantificar la incertidumbre del diagrama de persistencia $\hat{\mathcal{P}}$ construido.

![A la izquierda se observan los puntos del diagrama de persistencia en donde una caja de lado $2 \theta_n$ se centra en cada uno de ellos, representando la región de confianza para la cualidad topológica representada por ese punto. En color gris, se observan aquellas cualidades cuya región de confianza se interseca con la diagonal, ilustrando que estos puntos no son distinguibles de ruido, por otro lado, en color rojo se ilustran las regiones que no tienen contacto con la diagonal, siendo estas cualidades topológicas significativas. A la derecha se ilustra otra forma de interpretar estas regiones, posando una banda de tamaño $\sqrt{2} \theta_n$ sobre la diagonal que cubre toda la región del diagrama de persistencia en la que un punto presente en ella tendría su región de confianza intersecando la diagonal. Se observa que todos los puntos con caja gris en la figura de la izquierda aparecen dentro de la banda roja en la figura derecha. Créditos de la imagen: [@ConfidenceSetsForPersistenceDiagrams]](imagenes/intervalo-diagrama-persistencia.png){#fig-interval-persistence-diagram width=80%}
